CREATE DATABASE IF NOT EXISTS aula08;
USE aula08;

CREATE TABLE IF NOT EXISTS Produtos (
    Codigo INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Descricao VARCHAR(255),
    Preco DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS Clientes (
    Codigo INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telefone VARCHAR(20)
);
